In [47]:
import pandas as pd
import numpy as np
import plotly.express as px

## Import Data

In [2]:
df1 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202506-divvy-tripdata.csv")
df2 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202507-divvy-tripdata.csv")
df3 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202508-divvy-tripdata.csv")
df4 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202509-divvy-tripdata.csv")
df5 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202510-divvy-tripdata.csv")
df6 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202511-divvy-tripdata.csv")
df7 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202512-divvy-tripdata.csv")
df8 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202601-divvy-tripdata.csv")
df9 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202602-divvy-tripdata.csv")
df10 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202603-divvy-tripdata.csv")
df11 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202604-divvy-tripdata.csv")
df12 = pd.read_csv(r"E:\Bike Dataset\Data\copy\202605-divvy-tripdata.csv")

In [3]:
df = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12])
df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_length,day_of_week
0,B848EDADBCAD7B9B,electric_bike,6/1/2025 0:00,6/1/2025 0:08,NaN,NaN,NaN,NaN,41.950000,-87.690000,41.950000,-87.670000,casual,0:08:47,7
1,F2E9FB4ABF7653B6,electric_bike,6/1/2025 0:00,6/1/2025 0:05,Halsted St & Dickens Ave,CHI00291,Sheffield Ave & Wellington Ave,CHI00274,41.919936,-87.648830,41.936253,-87.652662,member,0:05:23,7
2,2DB8204C45EB9C52,electric_bike,6/1/2025 0:00,6/1/2025 0:06,Wabash Ave & Wacker Pl,CHI00416,NaN,NaN,41.886875,-87.626030,41.900000,-87.630000,member,0:05:46,7
3,2A9A8D8278A836B5,electric_bike,6/1/2025 0:00,6/1/2025 0:21,Michigan Ave & 14th St,CHI00342,NaN,NaN,41.864059,-87.623727,41.880000,-87.620000,casual,0:21:01,7
4,1486B0A11025F1DD,electric_bike,6/1/2025 0:00,6/1/2025 0:04,Wood St & Milwaukee Ave,CHI00329,NaN,NaN,41.907655,-87.672552,41.920000,-87.680000,casual,0:04:17,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653699,C2E1ADB72A12F004,electric_bike,5/31/2026 23:49,5/31/2026 23:53,NaN,NaN,Sheridan Rd & Noyes St (NU),CHI01114,42.050000,-87.680000,42.058239,-87.677432,casual,0:03:27,7
653700,839DEDA1F193CBD0,electric_bike,5/31/2026 23:51,5/31/2026 23:54,Marine Dr & Ainslie St,CHI00617,NaN,NaN,41.971600,-87.650154,41.960000,-87.650000,member,0:02:53,7
653701,FE79EB6E8CCAD1FC,electric_bike,5/31/2026 23:52,5/31/2026 23:56,Field Blvd & South Water St,CHI00383,Michigan Ave & Lake St,CHI00553,41.886349,-87.617517,41.886022,-87.624398,member,0:03:04,7
653702,3A1D2E7703426AAF,electric_bike,5/31/2026 23:53,5/31/2026 23:57,Dearborn St & Division St,CHI02125,Wells St & Walton St,CHI00260,41.904300,-87.629910,41.899930,-87.634430,member,0:03:38,7
653703,61B7ABE0F3607EA8,electric_bike,5/31/2026 23:57,5/31/2026 23:58,NaN,NaN,Halsted St & Fulton St,CHI02118,41.890000,-87.650000,41.886720,-87.647290,member,0:01:14,7

## Total Rides

In [5]:
total_rides = df['ride_id'].count()
total_rides

np.int64(5848498)

## Average Ride Length

In [6]:
df['ride_length'] = pd.to_timedelta(df['ride_length'], errors = 'coerce')
avg_ride_length  = df['ride_length'].mean()
avg_ride_length

Timedelta('0 days 00:15:58.286970')

## Maximum Ride Length

In [7]:
max_ride_length = df['ride_length'].max()
max_ride_length

Timedelta('1 days 02:14:54')

#### Total Rides & Average Ride Duration By Membership Type of Last 12 Months

In [10]:
result = df.groupby('member_casual').agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result

  member_casual  Total_Rides  Average_Ride_Duration
0        casual      2100105 0 days 00:22:13.311033
1        member      3748393 0 days 00:12:28.172732

In [51]:
fig = px.pie(result, names = 'member_casual', values = 'Total_Rides', title = 'Pie Chart')

fig.show()

#### Total Rides & Average Ride Duration By Rideable Type of Last 12 Months

In [11]:
result2 = df.groupby('rideable_type').agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result2

   rideable_type  Total_Rides  Average_Ride_Duration
0   classic_bike      1946071 0 days 00:23:36.336479
1  electric_bike      3902427 0 days 00:12:09.866232

In [52]:
fig1 = px.pie(result2, names = 'rideable_type', values = 'Total_Rides', title = 'Pie Chart')

fig1.show()

#### Total Rides & Average Ride Duration By Membership Type & Rideable Type of Last 12 Months

In [12]:
result3 = df.groupby(['member_casual', 'rideable_type']).agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result3

  member_casual  rideable_type  Total_Rides  Average_Ride_Duration
0        casual   classic_bike       661913 0 days 00:39:57.860735
1        casual  electric_bike      1438192 0 days 00:14:03.365377
2        member   classic_bike      1284158 0 days 00:15:10.415635
3        member  electric_bike      2464235 0 days 00:11:03.624998

#### Total Rides & Average Ride Duration Per Day of Last 12 Months

In [13]:
df['started_at'] = pd.to_datetime(df['started_at'])

In [14]:
df['date'] = df['started_at'].dt.date

In [15]:
result4 = df.groupby('date').agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result4

           date  Total_Rides  Average_Ride_Duration
0    2025-06-01        18754 0 days 00:20:17.109256
1    2025-06-02        20476 0 days 00:17:25.361349
2    2025-06-03        21671 0 days 00:16:51.567624
3    2025-06-04        10603 0 days 00:13:18.120531
4    2025-06-05        20536 0 days 00:15:45.234904
..          ...          ...                    ...
360  2026-05-27        26324 0 days 00:15:04.309375
361  2026-05-28        23950 0 days 00:13:32.979248
362  2026-05-29        26035 0 days 00:15:50.519800
363  2026-05-30        27662 0 days 00:17:38.534198
364  2026-05-31        21824 0 days 00:16:20.975989

[365 rows x 3 columns]

### Peak Day Per Month

In [16]:
df['year_month'] = df['started_at'].dt.strftime('%Y-%m')

In [17]:
summary = df.groupby(['year_month', 'date']).agg(total_ride = ('ride_id' , 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides = summary.groupby('year_month')['total_ride'].transform('max')

result5 = summary[summary['total_ride'] == max_rides]

result5

    year_month        date  total_ride       Average_Duration
27     2025-06  2025-06-28       31913 0 days 00:22:30.364365
47     2025-07  2025-07-18       30625 0 days 00:21:26.438367
62     2025-08  2025-08-02       32308 0 days 00:20:55.117958
118    2025-09  2025-09-27       30164 0 days 00:19:16.310137
133    2025-10  2025-10-12       30910 0 days 00:23:10.976285
167    2025-11  2025-11-15       19744 0 days 00:16:59.191602
199    2025-12  2025-12-17        8105 0 days 00:11:38.839111
220    2026-01  2026-01-07        9819 0 days 00:11:41.978001
271    2026-02  2026-02-27       13157 0 days 00:13:58.442882
293    2026-03  2026-03-21       21648 0 days 00:19:59.600378
326    2026-04  2026-04-23       25472 0 days 00:15:46.999136
349    2026-05  2026-05-16       30163 0 days 00:20:23.651195

#### Total Rides & Average Ride Duration Per Day By Membership Type of Last 12 Months

In [19]:
result6 = df.groupby(['year_month', 'date', 'member_casual']).agg(Total_Rides = ('ride_id', 'count'), 
                                                                  Average_Ride_Duration = ('ride_length', 'mean')).reset_index()

result6

    year_month        date member_casual  Total_Rides  Average_Ride_Duration
0      2025-06  2025-06-01        casual         9112 0 days 00:26:55.127743
1      2025-06  2025-06-01        member         9642 0 days 00:14:00.968989
2      2025-06  2025-06-02        casual         7332 0 days 00:25:24.306737
3      2025-06  2025-06-02        member        13144 0 days 00:12:58.195526
4      2025-06  2025-06-03        casual         7231 0 days 00:25:12.381551
..         ...         ...           ...          ...                    ...
725    2026-05  2026-05-29        member        16151 0 days 00:12:41.771902
726    2026-05  2026-05-30        casual        13078 0 days 00:22:08.230845
727    2026-05  2026-05-30        member        14584 0 days 00:13:36.687465
728    2026-05  2026-05-31        casual         9798 0 days 00:20:15.682588
729    2026-05  2026-05-31        member        12026 0 days 00:13:09.752369

[730 rows x 5 columns]

### Peak Day Per Month By Membership Types

In [20]:
summary1 = df.groupby(['year_month', 'date', 'member_casual']).agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides1 = summary1.groupby(['year_month', 'member_casual'])['Total_ride'].transform('max')

result7 = summary1[summary1['Total_ride'] == max_rides1]

result7

    year_month        date member_casual  Total_ride       Average_Duration
21     2025-06  2025-06-11        member       16392 0 days 00:13:03.260736
54     2025-06  2025-06-28        casual       18006 0 days 00:28:15.389981
68     2025-07  2025-07-05        casual       18240 0 days 00:29:15.061184
103    2025-07  2025-07-22        member       17179 0 days 00:13:52.363699
124    2025-08  2025-08-02        casual       17666 0 days 00:26:34.041548
163    2025-08  2025-08-21        member       17059 0 days 00:13:05.960079
236    2025-09  2025-09-27        casual       15391 0 days 00:24:32.522643
243    2025-09  2025-09-30        member       17862 0 days 00:12:39.446254
245    2025-10  2025-10-01        member       17821 0 days 00:12:19.132259
266    2025-10  2025-10-12        casual       17508 0 days 00:29:28.451336
315    2025-11  2025-11-05        member       14682 0 days 00:15:04.870657
334    2025-11  2025-11-15        casual        8196 0 days 00:22:33.502074
399    2025-12  2025-12-17        member        6700 0 days 00:10:47.174626
404    2025-12  2025-12-20        casual        1724 0 days 00:21:56.621229
441    2026-01  2026-01-07        member        8107 0 days 00:10:48.418033
444    2026-01  2026-01-09        casual        1930 0 days 00:14:49.756994
525    2026-02  2026-02-18        member        9889 0 days 00:11:57.047729
542    2026-02  2026-02-27        casual        3769 0 days 00:19:13.707614
586    2026-03  2026-03-21        casual       10441 0 days 00:25:28.850684
605    2026-03  2026-03-30        member       14090 0 days 00:13:41.479985
652    2026-04  2026-04-23        casual        8379 0 days 00:22:06.432151
653    2026-04  2026-04-23        member       17093 0 days 00:12:41.000819
716    2026-05  2026-05-25        casual       16054 0 days 00:26:31.584776
721    2026-05  2026-05-27        member       17860 0 days 00:12:44.389585

#### Total Rides & Average Ride Duration Per Day By Rideable Type of Last 12 Months

In [21]:
result8 = df.groupby(['year_month', 'date', 'rideable_type']).agg(Total_Rides = ('ride_id', 'count'), 
                                                                  Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result8

    year_month        date  rideable_type  Total_Rides  Average_Ride_Duration
0      2025-06  2025-06-01   classic_bike         7465 0 days 00:29:27.541326
1      2025-06  2025-06-01  electric_bike        11289 0 days 00:14:13.128797
2      2025-06  2025-06-02   classic_bike         8331 0 days 00:24:05.588644
3      2025-06  2025-06-02  electric_bike        12145 0 days 00:12:50.820913
4      2025-06  2025-06-03   classic_bike         8512 0 days 00:24:08.730028
..         ...         ...            ...          ...                    ...
725    2026-05  2026-05-29  electric_bike        18239 0 days 00:12:43.898952
726    2026-05  2026-05-30   classic_bike         8788 0 days 00:26:08.171711
727    2026-05  2026-05-30  electric_bike        18874 0 days 00:13:41.239800
728    2026-05  2026-05-31   classic_bike         7232 0 days 00:21:09.128871
729    2026-05  2026-05-31  electric_bike        14592 0 days 00:13:58.163377

[730 rows x 5 columns]

### Peak day Per Month By Rideable Type

In [22]:
summary2 = df.groupby(['year_month', 'date', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides2 = summary2.groupby(['year_month', 'rideable_type'])['Total_ride'].transform('max')

result9 = summary2[summary2['Total_ride'] == max_rides2]

result9

    year_month        date  rideable_type  Total_ride       Average_Duration
54     2025-06  2025-06-28   classic_bike       12102 0 days 00:34:02.816724
55     2025-06  2025-06-28  electric_bike       19811 0 days 00:15:27.364090
82     2025-07  2025-07-12   classic_bike       10917 0 days 00:32:12.107080
95     2025-07  2025-07-18  electric_bike       20093 0 days 00:14:00.529786
124    2025-08  2025-08-02   classic_bike       12307 0 days 00:29:46.145851
125    2025-08  2025-08-02  electric_bike       20001 0 days 00:15:28.366281
236    2025-09  2025-09-27   classic_bike       10370 0 days 00:27:45.358823
237    2025-09  2025-09-27  electric_bike       19794 0 days 00:14:49.621501
266    2025-10  2025-10-12   classic_bike       10850 0 days 00:38:48.277419
267    2025-10  2025-10-12  electric_bike       20060 0 days 00:14:44.011316
315    2025-11  2025-11-05  electric_bike       13130 0 days 00:10:06.556511
334    2025-11  2025-11-15   classic_bike        7328 0 days 00:23:54.885371
398    2025-12  2025-12-17   classic_bike        2733 0 days 00:14:42.526161
399    2025-12  2025-12-17  electric_bike        5372 0 days 00:10:05.388495
441    2026-01  2026-01-07  electric_bike        6595 0 days 00:09:20.108112
452    2026-01  2026-01-13   classic_bike        3321 0 days 00:19:05.128876
524    2026-02  2026-02-18   classic_bike        4870 0 days 00:17:38.676386
543    2026-02  2026-02-27  electric_bike        8973 0 days 00:11:38.532040
586    2026-03  2026-03-21   classic_bike        7027 0 days 00:29:14.044115
605    2026-03  2026-03-30  electric_bike       14645 0 days 00:13:15.642744
652    2026-04  2026-04-23   classic_bike        7382 0 days 00:24:11.530615
653    2026-04  2026-04-23  electric_bike       18090 0 days 00:12:21.114593
699    2026-05  2026-05-16  electric_bike       21102 0 days 00:15:23.189223
716    2026-05  2026-05-25   classic_bike        9303 0 days 00:32:36.826830

#### Total Rides & Average Ride Duration Per Day By Membership Type & Rideable Type of Last 12 Months

In [23]:
result10 = df.groupby(['year_month', 'date', 'member_casual', 'rideable_type']).agg(Total_Rides = ('ride_id', 'count'), 
                                                                                    Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result10

,year_month,date,member_casual,rideable_type,Total_Rides,Average_Ride_Duration
0,2025-06,2025-06-01,casual,classic_bike,3641,0 days 00:42:37.714089
1,2025-06,2025-06-01,casual,electric_bike,5471,0 days 00:16:27.828002
2,2025-06,2025-06-01,member,classic_bike,3824,0 days 00:16:55.182792
3,2025-06,2025-06-01,member,electric_bike,5818,0 days 00:12:06.463389
4,2025-06,2025-06-02,casual,classic_bike,2950,0 days 00:40:59.874576
...,...,...,...,...,...,...
1455,2026-05,2026-05-30,member,electric_bike,9759,0 days 00:12:12.699661
1456,2026-05,2026-05-31,casual,classic_bike,3078,0 days 00:28:58.889538
1457,2026-05,2026-05-31,casual,electric_bike,6720,0 days 00:16:16.035119
1458,2026-05,2026-05-31,member,classic_bike,4154,0 days 00:15:21.049109
1459,2026-05,2026-05-31,member,electric_bike,7872,0 days 00:12:00.467987

### Peak Day Per Month By Membership Type & Rideable Type

In [24]:
summary3 = df.groupby(['year_month', 'date', 'member_casual', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), 
                                                                                    Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides3 = summary3.groupby(['year_month', 'member_casual', 'rideable_type'])['Total_ride'].transform('max')

result11 = summary3[summary3['Total_ride'] == max_rides3]

result11

,year_month,date,member_casual,rideable_type,Total_ride,Average_Duration
42,2025-06,2025-06-11,member,classic_bike,6126,0 days 00:15:08.293503
43,2025-06,2025-06-11,member,electric_bike,10266,0 days 00:11:48.650301
81,2025-06,2025-06-21,casual,electric_bike,10914,0 days 00:16:17.537474
108,2025-06,2025-06-28,casual,classic_bike,7144,0 days 00:44:54.468645
122,2025-07,2025-07-01,member,classic_bike,6202,0 days 00:14:37.994195
136,2025-07,2025-07-05,casual,classic_bike,6901,0 days 00:46:28.476597
137,2025-07,2025-07-05,casual,electric_bike,11339,0 days 00:18:46.116853
211,2025-07,2025-07-23,member,electric_bike,11316,0 days 00:11:17.916666
248,2025-08,2025-08-02,casual,classic_bike,6912,0 days 00:40:42.785300
249,2025-08,2025-08-02,casual,electric_bike,10754,0 days 00:17:28.522038
271,2025-08,2025-08-07,member,electric_bike,10862,0 days 00:11:44.803903
346,2025-08,2025-08-26,member,classic_bike,6308,0 days 00:14:14.453392
467,2025-09,2025-09-25,member,electric_bike,11787,0 days 00:11:18.699923
472,2025-09,2025-09-27,casual,classic_bike,5386,0 days 00:39:25.335128
473,2025-09,2025-09-27,casual,electric_bike,10005,0 days 00:16:31.894152
486,2025-09,2025-09-30,member,classic_bike,6519,0 days 00:14:37.765148
490,2025-10,2025-10-01,member,classic_bike,6288,0 days 00:13:41.295165
495,2025-10,2025-10-02,member,electric_bike,11860,0 days 00:11:24.397470
532,2025-10,2025-10-12,casual,classic_bike,6204,0 days 00:53:21.240328
533,2025-10,2025-10-12,casual,electric_bike,11304,0 days 00:16:22.090498
613,2025-11,2025-11-01,casual,electric_bike,5510,0 days 00:12:57.500544
630,2025-11,2025-11-05,member,classic_bike,4901,0 days 00:24:42.342583
631,2025-11,2025-11-05,member,electric_bike,9781,0 days 00:10:15.514773
668,2025-11,2025-11-15,casual,classic_bike,3110,0 days 00:35:49.967524
798,2025-12,2025-12-17,member,classic_bike,2387,0 days 00:11:39.525764
799,2025-12,2025-12-17,member,electric_bike,4313,0 days 00:10:18.201252
809,2025-12,2025-12-20,casual,electric_bike,1236,0 days 00:11:13.350323
820,2025-12,2025-12-23,casual,classic_bike,544,0 days 00:25:39.115808
883,2026-01,2026-01-07,member,electric_bike,5323,0 days 00:09:21.078902
888,2026-01,2026-01-09,casual,classic_bike,549,0 days 00:28:14.105646
889,2026-01,2026-01-09,casual,electric_bike,1381,0 days 00:09:29.997827
906,2026-01,2026-01-13,member,classic_bike,2897,0 days 00:14:11.775629
1036,2026-02,2026-02-15,casual,classic_bike,1474,0 days 00:38:07.520352
1050,2026-02,2026-02-18,member,classic_bike,3955,0 days 00:13:48.363843
1085,2026-02,2026-02-27,casual,electric_bike,2656,0 days 00:13:11.657379
1087,2026-02,2026-02-27,member,electric_bike,6317,0 days 00:10:59.377236
1172,2026-03,2026-03-21,casual,classic_bike,3377,0 days 00:41:30.293455
1173,2026-03,2026-03-21,casual,electric_bike,7064,0 days 00:17:49.225509
1210,2026-03,2026-03-30,member,classic_bike,4566,0 days 00:17:37.478098
1211,2026-03,2026-03-30,member,electric_bike,9524,0 days 00:11:48.337673
1260,2026-04,2026-04-12,casual,classic_bike,2432,0 days 00:42:18.383634
1305,2026-04,2026-04-23,casual,electric_bike,6181,0 days 00:14:09.668338
1306,2026-04,2026-04-23,member,classic_bike,5184,0 days 00:15:36.115740
1307,2026-04,2026-04-23,member,electric_bike,11909,0 days 00:11:24.773112
1432,2026-05,2026-05-25,casual,classic_bike,4860,0 days 00:44:53.460699
1433,2026-05,2026-05-25,casual,electric_bike,11194,0 days 00:18:33.193049
1442,2026-05,2026-05-27,member,classic_bike,5832,0 days 00:15:28.921639
1443,2026-05,2026-05-27,member,electric_bike,12028,0 days 00:11:24.613152

#### Total Rides & Average Ride Duration Per Month of Last 12 Months

In [25]:
result12 = df.groupby(['year_month']).agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result12

   year_month  Total_Rides  Average_Ride_Duration
0     2025-06       678801 0 days 00:18:17.742674
1     2025-07       763458 0 days 00:18:01.768216
2     2025-08       790317 0 days 00:17:35.378739
3     2025-09       714562 0 days 00:15:59.923929
4     2025-10       646096 0 days 00:15:11.312772
5     2025-11       356512 0 days 00:13:43.334389
6     2025-12       140545 0 days 00:12:55.673086
7     2026-01       137782 0 days 00:13:37.465409
8     2026-02       201454 0 days 00:12:04.521955
9     2026-03       317015 0 days 00:13:46.552522
10    2026-04       448287 0 days 00:13:53.744982
11    2026-05       653669 0 days 00:16:00.387624

#### Total Rides & Average Ride Duration Per Month By Membership Type of Last 12 Months

In [26]:
result12 = df.groupby(['year_month', 'member_casual']).agg(Total_Rides = ('ride_id', 'count'), Average_Ride_Duration = ('ride_length', 'mean')).reset_index()
result12

   year_month member_casual  Total_Rides  Average_Ride_Duration
0     2025-06        casual       292006 0 days 00:25:23.039112
1     2025-06        member       386795 0 days 00:12:56.670499
2     2025-07        casual       323352 0 days 00:24:23.691636
3     2025-07        member       440106 0 days 00:13:21.163767
4     2025-08        casual       337878 0 days 00:23:36.497040
5     2025-08        member       452439 0 days 00:13:05.698341
6     2025-09        casual       265268 0 days 00:21:35.570988
7     2025-09        member       449294 0 days 00:12:41.754303
8     2025-10        casual       224038 0 days 00:20:28.160312
9     2025-10        member       422058 0 days 00:12:23.122881
10    2025-11        casual        99091 0 days 00:17:59.651218
11    2025-11        member       257421 0 days 00:12:04.669721
12    2025-12        casual        28090 0 days 00:16:58.124670
13    2025-12        member       112455 0 days 00:11:55.111395
14    2026-01        casual        24740 0 days 00:17:40.320412
15    2026-01        member       113042 0 days 00:12:44.314962
16    2026-02        casual        41173 0 days 00:16:53.539892
17    2026-02        member       160281 0 days 00:10:50.278997
18    2026-03        casual        87850 0 days 00:20:05.316357
19    2026-03        member       229165 0 days 00:11:21.354072
20    2026-04        casual       131526 0 days 00:19:29.840153
21    2026-04        member       316761 0 days 00:11:34.191017
22    2026-05        casual       245093 0 days 00:21:51.087354
23    2026-05        member       408576 0 days 00:12:30.012935

#### Peak Month By Membership Type

In [27]:
summary4 = df.groupby(['year_month', 'member_casual']).agg(Total_ride = ('ride_id' , 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides4 = summary4.groupby(['member_casual'])['Total_ride'].transform('max')

result13 = summary4[summary4['Total_ride'] == max_rides4]

result13

  year_month member_casual  Total_ride       Average_Duration
4    2025-08        casual      337878 0 days 00:23:36.497040
5    2025-08        member      452439 0 days 00:13:05.698341

#### Total Rides & Average Ride Duration Per Month By Rideable Type of Last 12 Months

In [28]:
result14 = df.groupby(['year_month', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()
result14

   year_month  rideable_type  Total_ride       Average_Duration
0     2025-06   classic_bike      254053 0 days 00:26:55.232376
1     2025-06  electric_bike      424748 0 days 00:13:08.218411
2     2025-07   classic_bike      265258 0 days 00:26:55.823387
3     2025-07  electric_bike      498200 0 days 00:13:17.419749
4     2025-08   classic_bike      281050 0 days 00:24:49.297623
5     2025-08  electric_bike      509267 0 days 00:13:35.911225
6     2025-09   classic_bike      239235 0 days 00:22:31.699542
7     2025-09  electric_bike      475327 0 days 00:12:42.740856
8     2025-10   classic_bike      209951 0 days 00:22:37.383170
9     2025-10  electric_bike      436145 0 days 00:11:36.583895
10    2025-11   classic_bike      115404 0 days 00:20:40.760711
11    2025-11  electric_bike      241108 0 days 00:10:23.544026
12    2025-12   classic_bike       44869 0 days 00:19:49.590652
13    2025-12  electric_bike       95676 0 days 00:09:41.558917
14    2026-01   classic_bike       43969 0 days 00:23:07.267438
15    2026-01  electric_bike       93813 0 days 00:09:10.406201
16    2026-02   classic_bike       66889 0 days 00:16:24.210483
17    2026-02  electric_bike      134565 0 days 00:09:55.437082
18    2026-03   classic_bike       96093 0 days 00:20:27.355894
19    2026-03  electric_bike      220922 0 days 00:10:52.217696
20    2026-04   classic_bike      133357 0 days 00:20:39.510321
21    2026-04  electric_bike      314930 0 days 00:11:01.923789
22    2026-05   classic_bike      195943 0 days 00:24:08.216282
23    2026-05  electric_bike      457726 0 days 00:12:31.558301

### Peak Month By Rideable type

In [29]:
summary5 = df.groupby(['year_month', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides5 = summary5.groupby(['rideable_type'])['Total_ride'].transform('max')

result15 = summary5[summary5['Total_ride'] == max_rides5]

result15

  year_month  rideable_type  Total_ride       Average_Duration
4    2025-08   classic_bike      281050 0 days 00:24:49.297623
5    2025-08  electric_bike      509267 0 days 00:13:35.911225

#### Total Rides & Average Ride Duration Per Month By Rideable Type & Membership Type of Last 12 Months

In [30]:
result16 = df.groupby(['year_month', 'member_casual', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), 
                                                                            Average_Duration = ('ride_length', 'mean')).reset_index()
result16

   year_month member_casual  rideable_type  Total_ride       Average_Duration
0     2025-06        casual   classic_bike      110232 0 days 00:42:16.452463
1     2025-06        casual  electric_bike      181774 0 days 00:15:08.481581
2     2025-06        member   classic_bike      143821 0 days 00:15:09.160713
3     2025-06        member  electric_bike      242974 0 days 00:11:38.246985
4     2025-07        casual   classic_bike      109560 0 days 00:42:10.003386
5     2025-07        casual  electric_bike      213792 0 days 00:15:17.248760
6     2025-07        member   classic_bike      155698 0 days 00:16:12.542415
7     2025-07        member  electric_bike      284408 0 days 00:11:47.343225
8     2025-08        casual   classic_bike      118154 0 days 00:38:26.361291
9     2025-08        casual  electric_bike      219724 0 days 00:15:37.982992
10    2025-08        member   classic_bike      162896 0 days 00:14:56.653601
11    2025-08        member  electric_bike      289543 0 days 00:12:03.275254
12    2025-09        casual   classic_bike       81197 0 days 00:37:55.255440
13    2025-09        casual  electric_bike      184071 0 days 00:14:23.414709
14    2025-09        member   classic_bike      158038 0 days 00:14:37.193611
15    2025-09        member  electric_bike      291256 0 days 00:11:39.115946
16    2025-10        casual   classic_bike       66635 0 days 00:38:22.900097
17    2025-10        casual  electric_bike      157403 0 days 00:12:53.179875
18    2025-10        member   classic_bike      143316 0 days 00:15:17.763585
19    2025-10        member  electric_bike      278742 0 days 00:10:53.330861
20    2025-11        casual   classic_bike       27278 0 days 00:36:39.709639
21    2025-11        casual  electric_bike       71813 0 days 00:10:54.253937
22    2025-11        member   classic_bike       88126 0 days 00:15:43.964173
23    2025-11        member  electric_bike      169295 0 days 00:10:10.516959
24    2025-12        casual   classic_bike        7042 0 days 00:39:40.084777
25    2025-12        casual  electric_bike       21048 0 days 00:09:22.455577
26    2025-12        member   classic_bike       37827 0 days 00:16:07.964311
27    2025-12        member  electric_bike       74628 0 days 00:09:46.946802
28    2026-01        casual   classic_bike        5902 0 days 00:46:11.426296
29    2026-01        casual  electric_bike       18838 0 days 00:08:44.225979
30    2026-01        member   classic_bike       38067 0 days 00:19:32.664092
31    2026-01        member  electric_bike       74975 0 days 00:09:16.984168
32    2026-02        casual   classic_bike       11620 0 days 00:33:38.455938
33    2026-02        casual  electric_bike       29553 0 days 00:10:18.415050
34    2026-02        member   classic_bike       55269 0 days 00:12:46.766125
35    2026-02        member  electric_bike      105012 0 days 00:09:48.970508
36    2026-03        casual   classic_bike       23886 0 days 00:40:20.426860
37    2026-03        casual  electric_bike       63964 0 days 00:12:31.559095
38    2026-03        member   classic_bike       72207 0 days 00:13:52.689268
39    2026-03        member  electric_bike      156958 0 days 00:10:11.733788
40    2026-04        casual   classic_bike       34023 0 days 00:39:21.259912
41    2026-04        casual  electric_bike       97503 0 days 00:12:34.102437
42    2026-04        member   classic_bike       99334 0 days 00:14:15.298608
43    2026-04        member  electric_bike      217427 0 days 00:10:20.587180
44    2026-05        casual   classic_bike       66384 0 days 00:41:24.909210
45    2026-05        casual  electric_bike      178709 0 days 00:14:35.054529
46    2026-05        member   classic_bike      129559 0 days 00:15:17.031082
47    2026-05        member  electric_bike      279017 0 days 00:11:12.459581

#### Peak Month By Membership Type & Rideable Type

In [31]:
summary6 = df.groupby(['year_month', 'member_casual', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), 
                                                                            Average_Duration = ('ride_length', 'mean')).reset_index()

max_rides6 = summary6.groupby(['member_casual', 'rideable_type'])['Total_ride'].transform(max)

result17 = summary6[summary6['Total_ride'] == max_rides6]

result17

   year_month member_casual  rideable_type  Total_ride       Average_Duration
8     2025-08        casual   classic_bike      118154 0 days 00:38:26.361291
9     2025-08        casual  electric_bike      219724 0 days 00:15:37.982992
10    2025-08        member   classic_bike      162896 0 days 00:14:56.653601
15    2025-09        member  electric_bike      291256 0 days 00:11:39.115946

### Total Rides Per Hour

In [32]:
df['started_at'].astype(str).head()

0    2025-06-01 00:00:00
1    2025-06-01 00:00:00
2    2025-06-01 00:00:00
3    2025-06-01 00:00:00
4    2025-06-01 00:00:00
Name: started_at, dtype: str

In [21]:
df['started_at'].head()

0    6/1/2025 0:00
1    6/1/2025 0:00
2    6/1/2025 0:00
3    6/1/2025 0:00
4    6/1/2025 0:00
Name: started_at, dtype: str

In [33]:
df['started_at'] = pd.to_datetime(df['started_at'], format = '%m/%d/%Y %H:%M')

In [34]:
df['hour'] = df['started_at'].dt.hour

In [35]:
result18 = df.groupby('hour').agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean')).reset_index()
result18

    hour  Total_ride       Average_Duration
0      0       75504 0 days 00:16:52.889502
1      1       47747 0 days 00:17:49.855589
2      2       30427 0 days 00:18:41.805205
3      3       18127 0 days 00:21:34.000220
4      4       17002 0 days 00:15:10.708563
5      5       48395 0 days 00:12:41.959520
6      6      133519 0 days 00:12:04.138616
7      7      261653 0 days 00:12:10.639610
8      8      347209 0 days 00:12:37.192662
9      9      247245 0 days 00:14:38.991886
10    10      237225 0 days 00:17:14.878490
11    11      286901 0 days 00:17:55.292512
12    12      332092 0 days 00:17:19.582154
13    13      333134 0 days 00:17:42.542181
14    14      344300 0 days 00:18:11.813043
15    15      411983 0 days 00:16:56.199675
16    16      541027 0 days 00:16:08.131950
17    17      606015 0 days 00:15:55.283773
18    18      485449 0 days 00:15:56.785617
19    19      346824 0 days 00:15:40.535969
20    20      245791 0 days 00:15:23.948057
21    21      197696 0 days 00:15:20.792980
22    22      152598 0 days 00:16:07.268384
23    23      100635 0 days 00:16:44.192954

#### Total Rides Per Hour By Membership Type

In [26]:
result19 = df.groupby(['hour', 'member_casual']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length','mean')).reset_index()
result19

    hour member_casual  Total_ride       Average_duration
0      0        casual       41533 0 days 00:20:47.789853
1      0        member       33971 0 days 00:12:05.699949
2      1        casual       26812 0 days 00:22:31.133679
3      1        member       20935 0 days 00:11:49.391967
4      2        casual       17805 0 days 00:23:10.603931
5      2        member       12622 0 days 00:12:22.629060
6      3        casual        9894 0 days 00:28:01.450171
7      3        member        8233 0 days 00:13:48.382606
8      4        casual        7812 0 days 00:19:25.199180
9      4        member        9190 0 days 00:11:34.377693
10     5        casual       12304 0 days 00:17:58.804210
11     5        member       36091 0 days 00:10:53.942090
12     6        casual       27763 0 days 00:15:26.463170
13     6        member      105756 0 days 00:11:11.024499
14     7        casual       51443 0 days 00:15:28.030635
15     7        member      210210 0 days 00:11:22.333694
16     8        casual       74058 0 days 00:17:05.005954
17     8        member      273151 0 days 00:11:24.581846
18     9        casual       73138 0 days 00:22:30.909773
19     9        member      174107 0 days 00:11:20.750974
20    10        casual       88251 0 days 00:25:45.271656
21    10        member      148974 0 days 00:12:12.525682
22    11        casual      112588 0 days 00:26:09.569119
23    11        member      174313 0 days 00:12:36.041425
24    12        casual      133591 0 days 00:24:52.678848
25    12        member      198501 0 days 00:12:14.648475
26    13        casual      138225 0 days 00:25:06.364543
27    13        member      194909 0 days 00:12:27.793524
28    14        casual      145768 0 days 00:25:16.067531
29    14        member      198532 0 days 00:13:00.312992
30    15        casual      161788 0 days 00:23:10.187300
31    15        member      250195 0 days 00:12:54.361470
32    16        casual      185672 0 days 00:21:48.674005
33    16        member      355355 0 days 00:13:10.199673
34    17        casual      201066 0 days 00:21:20.075422
35    17        member      404949 0 days 00:13:14.017644
36    18        casual      172097 0 days 00:21:15.817538
37    18        member      313352 0 days 00:13:01.569129
38    19        casual      129471 0 days 00:20:37.120590
39    19        member      217353 0 days 00:12:43.868945
40    20        casual       93969 0 days 00:20:10.023582
41    20        member      151822 0 days 00:12:26.883923
42    21        casual       79772 0 days 00:19:53.400265
43    21        member      117924 0 days 00:12:16.382441
44    22        casual       67436 0 days 00:20:39.323729
45    22        member       85162 0 days 00:12:31.839858
46    23        casual       47849 0 days 00:21:12.637714
47    23        member       52786 0 days 00:12:40.855454

#### Peak Hour By Membership Type

In [38]:
summary7 = df.groupby(['hour', 'member_casual']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

max_rides7 = summary7.groupby('member_casual')['Total_ride'].transform(max)

result20 = summary7[summary7['Total_ride'] == max_rides7]

result20

    hour member_casual  Total_ride       Average_duration
34    17        casual      201066 0 days 00:21:20.075422
35    17        member      404949 0 days 00:13:14.017644

### Total Rides Per Hour By Rideable Type

In [39]:
result21 = df.groupby(['hour', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()
result21

    hour  rideable_type  Total_ride       Average_duration
0      0   classic_bike       18595 0 days 00:34:40.308416
1      0  electric_bike       56909 0 days 00:11:04.110667
2      1   classic_bike       11193 0 days 00:39:38.660406
3      1  electric_bike       36554 0 days 00:11:09.337028
4      2   classic_bike        6808 0 days 00:44:40.826233
5      2  electric_bike       23619 0 days 00:11:12.429061
6      3   classic_bike        3895 0 days 00:59:13.799486
7      3  electric_bike       14232 0 days 00:11:15.540542
8      4   classic_bike        4030 0 days 00:31:53.107940
9      4  electric_bike       12972 0 days 00:09:59.294017
10     5   classic_bike       15019 0 days 00:21:11.291231
11     5  electric_bike       33376 0 days 00:08:52.763302
12     6   classic_bike       40002 0 days 00:18:14.676416
13     6  electric_bike       93517 0 days 00:09:25.640664
14     7   classic_bike       85710 0 days 00:16:46.695274
15     7  electric_bike      175943 0 days 00:09:56.160085
16     8   classic_bike      114049 0 days 00:17:31.061087
17     8  electric_bike      233160 0 days 00:10:13.448451
18     9   classic_bike       87332 0 days 00:21:31.612868
19     9  electric_bike      159913 0 days 00:10:53.650509
20    10   classic_bike       88075 0 days 00:25:05.221288
21    10  electric_bike      149150 0 days 00:12:37.134998
22    11   classic_bike      105620 0 days 00:25:53.981177
23    11  electric_bike      181281 0 days 00:13:16.393472
24    12   classic_bike      120456 0 days 00:24:49.289325
25    12  electric_bike      211636 0 days 00:13:03.624156
26    13   classic_bike      119341 0 days 00:25:32.146965
27    13  electric_bike      213793 0 days 00:13:20.404952
28    14   classic_bike      120129 0 days 00:26:43.640478
29    14  electric_bike      224171 0 days 00:13:37.534400
30    15   classic_bike      137514 0 days 00:24:36.564611
31    15  electric_bike      274469 0 days 00:13:05.548404
32    16   classic_bike      175136 0 days 00:22:56.741892
33    16  electric_bike      365891 0 days 00:12:52.548264
34    17   classic_bike      202850 0 days 00:22:24.682795
35    17  electric_bike      403165 0 days 00:12:39.360041
36    18   classic_bike      164847 0 days 00:23:01.624469
37    18  electric_bike      320602 0 days 00:12:18.342156
38    19   classic_bike      116192 0 days 00:22:59.431294
39    19  electric_bike      230632 0 days 00:11:59.421268
40    20   classic_bike       80444 0 days 00:22:55.287715
41    20  electric_bike      165347 0 days 00:11:44.363986
42    21   classic_bike       58978 0 days 00:23:44.077588
43    21  electric_bike      138718 0 days 00:11:46.814119
44    22   classic_bike       42813 0 days 00:26:47.513839
45    22  electric_bike      109785 0 days 00:11:57.591027
46    23   classic_bike       27043 0 days 00:30:24.852753
47    23  electric_bike       73592 0 days 00:11:42.623450

#### Peak Hour By Rideable Type

In [40]:
summary8 = df.groupby(['hour', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

max_rides8 = summary8.groupby('rideable_type')['Total_ride'].transform('max')

result22 = summary8[summary8['Total_ride'] == max_rides8]

result22

    hour  rideable_type  Total_ride       Average_duration
34    17   classic_bike      202850 0 days 00:22:24.682795
35    17  electric_bike      403165 0 days 00:12:39.360041

#### Total Rides Per Hour By Membership Type & Rideable Type

In [41]:
result23 = df.groupby(['hour', 'member_casual', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), 
                                                                      Average_duration = ('ride_length', 'mean')).reset_index()
result23

    hour member_casual  rideable_type  Total_ride       Average_duration
0      0        casual   classic_bike       10307 0 days 00:48:14.899485
1      0        casual  electric_bike       31226 0 days 00:11:44.116025
2      0        member   classic_bike        8288 0 days 00:17:47.278716
3      0        member  electric_bike       25683 0 days 00:10:15.471206
4      1        casual   classic_bike        6459 0 days 00:55:47.203594
..   ...           ...            ...         ...                    ...
91    22        member  electric_bike       60824 0 days 00:11:08.092874
92    23        casual   classic_bike       12878 0 days 00:44:56.112828
93    23        casual  electric_bike       34971 0 days 00:12:28.445883
94    23        member   classic_bike       14165 0 days 00:17:12.753406
95    23        member  electric_bike       38621 0 days 00:11:01.131612

[96 rows x 5 columns]

#### Peak Hour By Membership Type & Rideable Type

In [42]:
summary9 = df.groupby(['hour', 'member_casual', 'rideable_type']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

max_rides9 = summary9.groupby(['member_casual', 'rideable_type'])['Total_ride'].transform(max)

result24 = summary9[summary9['Total_ride'] == max_rides9]

result24

    hour member_casual  rideable_type  Total_ride       Average_duration
68    17        casual   classic_bike       62371 0 days 00:37:23.014301
69    17        casual  electric_bike      138695 0 days 00:14:07.042791
70    17        member   classic_bike      140479 0 days 00:15:45.834323
71    17        member  electric_bike      264470 0 days 00:11:53.376908

#### Total Rides Per Hour By Day of Week

In [43]:
result25 = df.groupby(['hour', 'day_of_week']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

result25

     hour  day_of_week  Total_ride       Average_duration
0       0            1        6742 0 days 00:19:27.473894
1       0            2        5610 0 days 00:18:32.330659
2       0            3        5687 0 days 00:16:06.821874
3       0            4        6626 0 days 00:14:51.248264
4       0            5        9815 0 days 00:15:51.477636
..    ...          ...         ...                    ...
163    23            3       11047 0 days 00:15:29.973658
164    23            4       15550 0 days 00:15:56.809839
165    23            5       22967 0 days 00:16:35.405712
166    23            6       22942 0 days 00:17:38.372286
167    23            7        9878 0 days 00:18:54.051224

[168 rows x 4 columns]

#### Peak Hour By Day of Week

In [44]:
summary10 = df.groupby(['hour', 'day_of_week']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

max_rides10 = summary10.groupby(['day_of_week'])['Total_ride'].transform('max')

result26 = summary10[summary10['Total_ride'] == max_rides10]

result26

     hour  day_of_week  Total_ride       Average_duration
110    15            6       73471 0 days 00:19:38.252984
111    15            7       66660 0 days 00:19:49.074512
119    17            1       93648 0 days 00:15:09.473966
120    17            2      100993 0 days 00:14:28.390423
121    17            3      100417 0 days 00:14:31.525030
122    17            4      100669 0 days 00:14:50.851155
123    17            5       88331 0 days 00:16:19.615197

#### Total Rides Per Hour By Month

In [45]:
result27 = df.groupby(['year_month', 'hour']).agg(Total_ride = ('ride_id', 'count'), Average_duration = ('ride_length', 'mean')).reset_index()

result27

    year_month  hour  Total_ride       Average_duration
0      2025-06     0        9683 0 days 00:20:54.976143
1      2025-06     1        5817 0 days 00:18:44.354993
2      2025-06     2        3667 0 days 00:22:35.993455
3      2025-06     3        2165 0 days 00:30:51.327944
4      2025-06     4        1930 0 days 00:17:40.641450
..         ...   ...         ...                    ...
283    2026-05    19       40714 0 days 00:16:03.640295
284    2026-05    20       28843 0 days 00:15:20.934611
285    2026-05    21       22752 0 days 00:14:58.333904
286    2026-05    22       17192 0 days 00:15:29.773848
287    2026-05    23       11408 0 days 00:15:49.733082

[288 rows x 4 columns]

#### Peak Hour By Month

In [46]:
summary11 = df.groupby(['year_month', 'hour']).agg(Total_ride = ('ride_id', 'count'), Average_Duration = ('ride_length', 'mean') ).reset_index()

max_rides11 = summary11.groupby(['year_month'])['Total_ride'].transform('max')

result28 = summary11[summary11['Total_ride'] == max_rides11]

result28

    year_month  hour  Total_ride       Average_Duration
17     2025-06    17       69571 0 days 00:18:06.071567
41     2025-07    17       78354 0 days 00:17:38.352745
65     2025-08    17       77859 0 days 00:17:05.811685
89     2025-09    17       75265 0 days 00:16:15.334790
113    2025-10    17       67307 0 days 00:14:55.507658
137    2025-11    17       34390 0 days 00:13:25.838877
161    2025-12    17       13678 0 days 00:14:26.169030
185    2026-01    17       14405 0 days 00:14:07.665532
209    2026-02    17       22209 0 days 00:13:02.458868
233    2026-03    17       34191 0 days 00:13:55.999649
257    2026-04    17       51671 0 days 00:14:17.221168
281    2026-05    17       67115 0 days 00:16:06.314713